[project]
name = "follow-elon"
version = "0.1.0"
description = "Twitter API client for following Elon and other users"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "requests>=2.31.0",
    "python-dotenv>=1.0.0",
]
