[project]
name = "follow-elon"
version = "0.1.0"
description = "X平台@elonmusk活动追踪程序"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "requests>=2.31.0",
    "python-dotenv>=1.0.0",
    "pytest>=7.4.0",
    "pytest-mock>=3.11.1",
    "responses>=0.23.3"
]
